spring:
  application:
    name: community

  datasource:
    url: jdbc:mysql://efub-community.cbosoki4qqbu.ap-northeast-2.rds.amazonaws.com:3306/community?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: admin
    password: mdmstj2395!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

